//! Engine protocol v1 types.
//!
//! `protocol_v1.rs` is generated by cargo-typify (run `contracts/generate.sh`). Its top-level
//! enum is untagged and JSON Schema `const`s become plain `serde_json::Value`, so serde alone
//! would accept e.g. `{"protocol":1,"type":"bogus"}` as `Shutdown`. Always parse with
//! [`parse_message`] / [`from_value`], which dispatch on `type` and enforce what the generated
//! code skips: `protocol == 1`, the `type`/`status`/`language` constants, and
//! docVersion/settingsVersion together on errors.
#[allow(clippy::all, dead_code, unused_imports)]
pub mod protocol_v1;

use protocol_v1::{CheckRequest, CheckResult, ErrorMessage, Ready, Shutdown};
use serde_json::Value;

pub const PROTOCOL: u64 = 1;

/// A validated protocol v1 message, tagged by its `type` field.
#[derive(Debug, Clone)]
pub enum Message {
    Ready(Ready),
    Check(CheckRequest),
    Result(CheckResult),
    Error(ErrorMessage),
    Shutdown(Shutdown),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseError(pub String);

impl std::fmt::Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}
impl std::error::Error for ParseError {}

fn err<T>(m: impl Into<String>) -> Result<T, ParseError> {
    Err(ParseError(m.into()))
}

pub fn parse_message(line: &str) -> Result<Message, ParseError> {
    from_value(serde_json::from_str(line).map_err(|e| ParseError(format!("not JSON: {e}")))?)
}

pub fn from_value(v: Value) -> Result<Message, ParseError> {
    if v.get("protocol").and_then(Value::as_u64) != Some(PROTOCOL) {
        return err("protocol must be 1");
    }
    fn de<T: serde::de::DeserializeOwned>(v: Value) -> Result<T, ParseError> {
        serde_json::from_value(v).map_err(|e| ParseError(format!("schema: {e}")))
    }
    let ty = v.get("type").and_then(Value::as_str).unwrap_or("").to_owned();
    match ty.as_str() {
        "ready" => {
            if v.get("language").and_then(Value::as_str) != Some("pl-PL") {
                return err("language must be pl-PL");
            }
            Ok(Message::Ready(de(v)?))
        }
        "check" => Ok(Message::Check(de(v)?)),
        "result" => {
            if v.get("status").and_then(Value::as_str) != Some("complete") {
                return err("status must be complete");
            }
            let r: CheckResult = de(v)?;
            if r.issues.iter().any(|i| i.end < i.start) {
                return err("issue end < start");
            }
            Ok(Message::Result(r))
        }
        "error" => {
            if v.get("docVersion").is_some() != v.get("settingsVersion").is_some() {
                return err("docVersion and settingsVersion must come together");
            }
            Ok(Message::Error(de(v)?))
        }
        "shutdown" => Ok(Message::Shutdown(de(v)?)),
        _ => err(format!("unknown type {ty:?}")),
    }
}
